# Generated by Django 3.2.4 on 2021-07-13 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_post_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='liked',
        ),
    ]
