# Generated by Django 3.2.4 on 2021-08-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_remove_post_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_liked',
            field=models.BooleanField(default=False),
        ),
    ]
