# Generated by Django 3.2.4 on 2021-08-23 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_post_user_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_liked',
        ),
    ]
