# Generated by Django 3.2.4 on 2021-08-23 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_remove_post_user_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
